### ISSUE TITLE
Get Ethereum address from Polyjuice address in Solidity

### ISSUE THREAD

**Issue by Kuzirashi** [RetricSu/godwoken-kicker#43]
Is there a way to get Ethereum address from Polyjuice address inside a smart-contract?

I've read https://github.com/nervosnetwork/godwoken/blob/master/docs/known_caveats_of_polyjuice.md and I know these methods for address translation exists in RPC (godwoken-web3) layer, but I wonder if it exists also in Solidity.

**Comment by TheWaWaR** [comment]
Based on brand new address format design, all (EoA/contract) addresses are `account_script_hash[..20]`. The new design is focus more on interoperability than ergonomic. By this design, all Ethereum addresses are meaningless, since you can not use them to interact with polyjuice.

However, you may want to know how a godwoken address is calculated:

``` yaml
eoa_account_script:
    code_hash: {eth,tron}_account_lock_hash
    hash_type: type
    args: layer1_script_hash
eoa_godwoken_address: blake2b(eoa_account_script)[..20]

# Normal contract account
normal_contract_account_script:
    code_hash: polyjuice_type_script_hash
    hash_type: type
    args: keccak256(rlp_encode(msg.sender, sender.nonce))[12..32]
normal_contract_godwoken_address:  blake2b(normal_contract_account_script)[..20]

# Create2 contract account
create2_contract_account_script:
    code_hash: polyjuice_type_script_hash
    hash_type: type
    args: keccak256(msg.sender + create2_salt + keccak256(init_code))[12..32]
create2_contract_godwoken_address: blake2b(create2_contract_account_script)[..20]
```
